### ISSUE TITLE
Can the trading mode set to live? 

### ISSUE THREAD

**Issue by mvperez** [mvberg/ib-gateway-docker#1]
Hi @mvberg, 
Thanks for this and this is very helpful. I successfully build the image, run a container and view it in VNC, all perfectly well as documented. 
Now, I'm wondering how to use the live trading mode? As you know, in live trading mode, we need to supply additional info in 2-fac mode, e.g. code sent in mobile or the printed card random numbers.
I know once we started a container, run vnc, do some modification in IB gateway settings, then wen can build a new image with these changes. But I still don't see how entering of 2-fac code can be done.
Thanks,
Marvin

**Comment by mvberg** [comment]
@marvinvperez sweet, nice to hear.

so, last i checked with the IBController project (not sure if they are still maintaining this), they did not want to touch 2FA - i know you can disable it, but this is risky ...

that said, i had an interesting automated solution in the past - it revolved around "captcha busting" - essentially:

* database your secret codes, keyed by "captcha" code 
* grab a screenshot of the 2FA image that is prompted after user/pass login
* upload it to [DeathByCaptcha](http://www.deathbycaptcha.com/user/login) via API 
* wait for the image translation (or you could do this yourself)
* take the response code, lookup the "secret", enter it in the Swing input box, and in you're in

of course this is assuming IB's 2FA impl is still based off that little pocket card? though, reading here it seems to now be SMS based (which is not great) https://github.com/ib-controller/ib-controller/issues/201 ?

if they still have the printed card offering, LMK. i will look for the code and share it in this repo.

**Comment by mvperez** [comment]
@mvberg Thanks for quick response. Yeah, the printed card still work along with new sms based. From the login window you can choose which one you want to use. It will be great if you share that repo of how to implement the bullets you describe. I can imagine your pretty helpful repo now will be more useful if we add this solution to handle the "captcha" for live trading mode. I have a team member that can help out if needed.

**Comment by mvperez** [comment]
I'll just disable the 2FA as a temporary solution. I will close this issue but still, look forward to seeing a solution on how to handle the "captcha".
