### ISSUE TITLE
⚠️ Needs to be updated to latest version of IB Gateway or will stop functioning 12/29/2021 ⚠️

### ISSUE THREAD

**Issue by leebailey88** [mvberg/ib-gateway-docker#28]
From IB:

"We are contacting you because you or one of your sub-accounts has logged in to our systems during the past 7 days using an older version of the Trader Workstation that is still not patched against a global vulnerability in Apache's Log4j software library, commonly known as 'Log4Shell'.

To secure your environment, it is important for you to download and install the latest 'TWS Latest' version of Trader Workstation.

**Due to the high risk nature of the vulnerability, we will discontinue operation of non-upgraded TWS installs on Wednesday, December 29.**

**Comment by d3an** [comment]
Pretty sure this repo is no longer maintained. You could try my [setup](https://github.com/d3an/ib-gateway-docker-v981). Its up-to-date with the latest stable.

**Comment by leebailey88** [comment]
Thanks, yours works well!
