### ISSUE TITLE
"No demo user account available"?

### ISSUE THREAD

**Issue by krumware** [mvberg/ib-gateway-docker#4]
Hi mvberg,
Have you seen an issue where there is "No demo user account available"?
I have tried manually specifying the user credentials in IBController.ini, but no luck.

For reference, I cloned the repo, built the container with `docker-compose build` and ran with `docker-compose up`. We tried this on both windows and linux machines, but each place prompts with "No demo user account available" upon connecting via VNC.  A little bit lost here as to whether this should be working out of the box, some direction would be greatly appreciated! TIA!

**Comment by krumware** [comment]
It looks like `fdemo` works as a user, but not `edemo`, do you know if this is expected?

**Comment by krumware** [comment]
We can log in manually with `fdemo`  over VNC, but it does look like `EDEMO` is reflected. 
![image](https://user-images.githubusercontent.com/17303782/52509013-8f57ef80-2bc4-11e9-90dd-f5e1cb90db5c.png)

**Comment by mvberg** [comment]
> A little bit lost here as to whether this should be working out of the box

it was 7 months ago :) - thank you for the detailed report! @krumware 

seems that IB has changed `edemo` to `fdemo`?

[updated the default login in docker-compose.yaml](https://github.com/mvberg/ib-gateway-docker/commit/0eaddacbe710ab2a0e63fafaec3e19a287de1c9b)

![fdemo_ftw](https://user-images.githubusercontent.com/649509/52977082-8c61b980-3391-11e9-99f1-b4a213766bf8.jpg)

does this work for you as well?

**Comment by mvberg** [comment]
> I have tried manually specifying the user credentials in IBController.ini, but no luck

the docs need to be updated to reflect this, the current behavior is a bit confusing - essentially you can override the variables "downstream" in the [docker-compose file](https://github.com/mvberg/ib-gateway-docker/blob/master/docker-compose.yml#L11) - which is why changing them in the INI had no effect.

PR's welcome

**Comment by krumware** [comment]
As far as I understand it, `edemo` is supposed to be the standard demo user, but `fdemo` is the "broker demo account" or something like that. It's entirely possible that, like you mentioned, the `edemo` user is simply no longer valid.
I did verify that login does also work with a real account.

We are still learning about this integration in general, and will contribute back as we can.

**Comment by krumware** [comment]
Closing this, I think it's safe to use `fdemo` instead of `edemo`
