### ISSUE TITLE
second vnc connection is rejected

### ISSUE THREAD

**Issue by yintechlabs** [mvberg/ib-gateway-docker#8]
I usually use vncviewer to monitor the ib-gateway in the container. The first vncviewer connection is fine, but second is always rejected. I got an 'End of stream' error for second connection.

For other vnc containers, I usually use 'vncviewer -shared' to solved this problem. but it does not work for this container. any idea?

**Comment by krumware** [comment]
Would it be expected that the second connection would share the same session as the first?  If so, we might be able to add the parameter `-alwaysshared` to the vnc launch args.
(frankly, my VNC knowledge is limited, @mvberg may be of better help here)

**Comment by yintechlabs** [comment]
Thanks
